flashcardz_app/auth.py
"""Routes for user authentication."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user

from . import login_manager
from .forms import LoginForm, RegistrationForm
from .models import User, db

# See this tutorial for more info on code: https://hackersandslackers.com/flask-login-user-authentication
# See this repo for sample code and file structure: https://github.com/toddbirchard/flasklogin-tutorial

# Blueprint Configuration
auth_bp = Blueprint(
    "auth_bp", __name__, template_folder="templates", static_folder="static"
)

@auth_bp.route('/register', methods = ['POST', 'GET'])
def register():
    """
        User registration page.
        GET requests serve sign-up page.
        POST requests validate form & user creation.
    """
    form = RegistrationForm()
    if form.validate_on_submit():
        # Check that email isn't already in the DB
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(
                email = form.email.data
            )
            user.set_password(form.password1.data)
            db.session.add(user)
            db.session.commit()
            login_user(user)
            return redirect(url_for('main_bp.my_decks', email=user.email))

    return render_template("registration.html", form=form, title="Register")


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
        Log-in page for registered users.
        GET requests serve Log-in page.
        POST requests validate and redirect user to dashboard.
    """
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            flash("Logged in successfully " + user.email)
            return redirect(url_for('main_bp.my_decks', email=user.email))
        else:
            flash("Invalid username or password")
            return redirect(url_for("auth_bp.login"))

    return render_template('login.html', form=form, title="Login")


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""

    flash("You must be logged in to view that page.")
    return redirect(url_for("auth_bp.login"))

flashcardz_app/routes.py
"""Logged-in page routes."""
from flask import Blueprint, redirect, render_template, url_for, make_response, Response, request
from flask_login import current_user, login_required, logout_user
import flask_login

from .forms import AddCardForm, CreateDecksForm

from .models import User, Deck, Card, db

# Blueprint Configuration
main_bp = Blueprint(
    "main_bp", __name__, template_folder="templates", static_folder="static"
)

# Instead of using decorator `@app.route('<path>')` for our routes we use `@main_bp.route('<path>')`
# This associates the route with the main_bp blueprint that is configured above and registered in `__init__.py`
# We can also using the decorator @login_required to require login to see these routes

@main_bp.route('/')
def home():
    if current_user.is_authenticated:  
        return redirect(url_for('main_bp.my_decks', email=current_user.email))
    else:
        return redirect(url_for("auth_bp.login"))

@main_bp.route('/<email>/mydecks')
@login_required
def my_decks(email):
    #step one, obtain id of user to obtain decks
    current_user = User.query.filter_by(email=email).first()
    #step two, get collection of all decks owned by logged in user
    user_decks = Deck.query.filter_by(owner_id=current_user.id).all()
    return render_template('my_decks.html', email=email, user_decks=user_decks, title="My Decks")

@main_bp.route('/<email>/decks/create', methods=['GET', 'POST'])
@login_required
def create_deck(email):
    form = CreateDecksForm()
    if form.validate_on_submit():
        current_user = User.query.filter_by(email=email).first()
        new_deck = Deck(name=form.deck_name.data, card_count=0, owner_id=current_user.id)
        db.session.add(new_deck)
        db.session.commit()
        return redirect(url_for('main_bp.my_decks', email=email))

    return render_template('create_deck.html', form=form, title="Create Deck")

@main_bp.route('/<email>/<deck_id>/decks/edit', methods=['GET', 'POST'])
@login_required
def edit_deck(email, deck_id):
    user_cards = Card.query.filter_by(deck_id=deck_id).all()
    deck= Deck.query.filter_by(id=deck_id).first()
    form = AddCardForm()

    #below logic used to calculate score for last attempt
    score_from_last_attempt = 0
    for card in user_cards:
        if(card.last_attempt == True):
            score_from_last_attempt += 1

    if (len(user_cards) == 0):
        percent_score = 0
    else:
        percent_score = round((score_from_last_attempt/len(user_cards))*100, 2)
    
    if form.validate_on_submit():
        new_card = Card(
            front=form.front.data, 
            back=form.back.data, 
            deck_id=deck_id, 
            attempts=0,
            correct=0,
            last_attempt=False,
        )
        deck.card_count += 1
        db.session.add(new_card)
        db.session.commit()
        return redirect(url_for('main_bp.edit_deck', email=email, deck_id=deck_id))

    return render_template('edit_deck.html', email=email, user_cards=user_cards, form=form, deck=deck, percent_score=percent_score)

@main_bp.route('/study/<deck_id>/<card_id>')
def study(deck_id, card_id):
    cards = Card.query.filter_by(deck_id=deck_id).order_by(Card.id).all()
    card_id = int(card_id)

    if card_id == -1:
        card_id = cards[0].id
        card = cards[0]
        return render_template('study.html', deck_id=deck_id, card_id=card_id, card=card)
    else:
        index = -1
        for ind, card in enumerate(cards):
            if card.id == card_id:
                index = ind + 1
                break
        
        if index >= len(cards) or index == -1:
            return redirect(url_for('main_bp.edit_deck', email=current_user.email, deck_id=deck_id))
        else:
            return render_template('study.html', deck_id=deck_id, card_id=cards[index].id, card=cards[index])


@main_bp.route("/delete-card?card_id=<card_id>&deck_id=<deck_id>", methods=["GET", "DELETE"])
@login_required
def delete_card(card_id, deck_id):
    Card.query.filter_by(id=card_id).delete()
    db.session.commit()
    return redirect(url_for('main_bp.edit_deck', email=current_user.email, deck_id=deck_id))


@main_bp.route("/record-score", methods=["PUT"])
@login_required
def record_score():
    data = request.json
    
    card = Card.query.filter_by(id=int(data["card_id"])).first()
    
    if(card.attempts == None):  #added to catch situation when attempt first set to None
        card.attempts = 1
    else:
        card.attempts += 1

    if data["correct"] == True:
        if(card.correct == None):  #added to catch situation when correct first set to None
            card.correct = 1
        else:
            card.correct += 1

        card.last_attempt = True
    else:
        card.last_attempt = False

    db.session.commit()

    return "Added"

@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for("auth_bp.login"))

@main_bp.errorhandler(404)
def not_found():
    """Page not found."""
    return "<h1>404: Not Found</h1>"

flashcardz_app/templates/create_deck.html
{% extends 'layout.html' %}
{% block content %}
   <h1 style="text-align: center; color: blue;">Create a New Deck</h1>
   <br>
   <form action="" method="post">
      {{ form.hidden_tag() }}
      <div>
         {{ form.deck_name(placeholder="Deck Name",
         style='width: 50%;
         font-weight: bold;
         padding: 12px 20px ;
         margin: 8px 0;
         border: 1px solid #ccc;
         border-radius: 4px;
         box-sizing: border-box') }}
         {% for error in form.deck_name.errors %}
         <p>{{ error }}</p>
         {% endfor %}
      </div>
      <br>
      <div>
         {{ form.submit(style ='width: 50%;') }}
      </div>
   </form>
   <a href="{{url_for('main_bp.my_decks', email=current_user.email)}}" class="my_decks">Go to My Decks</a>
{% endblock %}

flashcardz_app/templates/edit_deck.html
{% extends 'layout.html' %}
{% block content %}

   <div class="deck-info-container">
      <div class="title-btn">
         <h1>{{ deck.name }}</h1>
         <a href="{{ url_for('main_bp.study', deck_id=deck.id, card_id=-1) }}">
            <button>Study Deck</button>
         </a>
      </div>
      <h2>Cards: {{ deck.card_count }}</h2>
      <h2>Last Study Score: {{ percent_score }}%</h2>
   </div>


   <div class="card-info-container">
      <div class="title-btn">
         <h1>Cards</h1>
         <a href="#create-card-container">
            <button>New Card</button>
         </a>
      </div>

      <div class="card-container">
         {% if user_cards %}
            {% for card in user_cards %}
               <div class="edit-card-container">
                  <div class="card" flipped="false">
                     <div class="card-inner">
                        <div class="card-front">
                           <div class="side-text">
                              <h3>Front: </h3>
                              <p>{{ card.front }}</p>
                           </div>
                        </div>
                        <div class="card-back">
                           <div class="side-text">
                              <h3>Back: </h3>
                              <p>{{ card.back }}</p>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="delete-container">
                     <a class="delete-card" href="{{ url_for('main_bp.delete_card', card_id=card.id, deck_id=card.deck_id) }}">
                        Delete
                     </a>
                  </div>
               </div>
            {% endfor %} 
         {% else %}
            <p>No Cards yet</p>  
         {% endif %}
      </div>
   </div>

   <div id="create-card-container">
      <div class="edit-page-title">
         <h1>Create Card</h1>
         <p>Enter front and back text in the form below and press "Create Card"</p>
      </div>
         <form action="" method="post">
            {{ form.hidden_tag() }}
            <div>
               {{ form.front(placeholder="Front text",
               style='width: 100%;
               font-weight: bold;
               padding: 12px 20px ;
               margin: 8px 0;
               border: 1px solid #ccc;
               border-radius: 4px;
               box-sizing: border-box') }}
               {% for error in form.front.errors %}
               <p>{{ error }}</p>
               {% endfor %}
            </div>
            <br>
            <div>
               {{ form.back(placeholder="Back text",
               style='width: 100%;
               font-weight: bold;
               padding: 12px 20px ;
               margin: 8px 0;
               border: 1px solid #ccc;
               border-radius: 4px;
               box-sizing: border-box') }}
               {% for error in form.back.errors %}
               <p>{{ error }}</p>
               {% endfor %}
            </div>
            <br>
            <div>
               {{ form.submit(style ='width: 100%;') }}
            </div>
         </form>
   </div>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='flip-card.js') }}"></script>
{% endblock %}

flashcardz_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheet.css') }}">
    <title>{{ title }}</title>
</head>
<body>
    {% if current_user.is_authenticated %}
        <header>
            Logged in as {{ current_user.email }}
            <div class="nav-btns">
                <a href="{{ url_for('main_bp.my_decks', email=current_user.email)}}">
                    <button type="button">
                        My Decks
                    </button>
                </a> 
                <a href="{{ url_for('main_bp.logout')}}">
                    <button type="button" id="logout-btn">
                        Log Out
                    </button>
                </a> 
            </div>
        </header>
    {% endif %}
    {% block content %}{% endblock %}
    {% block scripts %}{% endblock %}
</body>
</html>

flashcardz_app/templates/login.html
{% extends 'layout.html' %}
{% block content %}
   <h1>FLASHCARDZ</h1>
   <h2>LOG IN </h2>
   <form action="" method="post">
      {{ form.hidden_tag() }}

      <div>
         EMAIL<br> 
         {{ form.email(placeholder="Email") }}
         {% for error in form.email.errors %}
         <p>{{ error }}</p>
         {% endfor %}
      </div>
      <br>

      <div>
         PASSWORD<br> 
         {{ form.password(placeholder="Password") }}
         {% for error in form.password.errors %}
         <p>{{ error }}</p>
         {% endfor %}
      </div>
      <br>

      <div>
         {{ form.submit }}
      </div>
      <br>

   </form>
   <p class="alt-auth"><a href="{{ url_for('auth_bp.register') }}">Don't have an account? Sign up!</a></p>
{% endblock %}

flashcardz_app/templates/my_cards.html
{% extends 'layout.html' %}
{% block content %}
   <header>You are logged in as {{ email }}</header>
   <h1>Edit Your Deck Here</h1>
   <h2> Below are the cards currently in your deck: </h2>

   {% if user_cards is none %}
      <p>No Cards yet</p>  
   {% else %}
      <div class="card-container">
         {% for card in user_cards %}
            <div class="card" flipped="false">
               <div class="card-inner">
                  <div class="card-front">
                     <h3>Front: </h3>
                     <p>{{ card.front }}</p>
                  </div>
                  <div class="card-back">
                     <h3>Back: </h3>
                     <p>{{ card.back }}</p>
                  </div>
               </div>
               <a class="edit-card" href="#">Edit</a>
            </div>
         {% endfor %} 
      </div>
   {% endif %}


   <br>
   <br>

   <h2 style="text-align: justify; color: blue;">Create a New Deck</h2>
   <br>
   <form action="" method="post">
      {{ form.hidden_tag() }}
      <div>
         {{ form.front(placeholder="front",
         style='width: 50%;
         font-weight: bold;
         padding: 12px 20px ;
         margin: 8px 0;
         border: 1px solid #ccc;
         border-radius: 4px;
         box-sizing: border-box') }}
         {% for error in form.front.errors %}
         <p>{{ error }}</p>
         {% endfor %}
      </div>
      <br>
      <div>
         {{ form.back(placeholder="back",
         style='width: 50%;
         font-weight: bold;
         padding: 12px 20px ;
         margin: 8px 0;
         border: 1px solid #ccc;
         border-radius: 4px;
         box-sizing: border-box') }}
         {% for error in form.back.errors %}
         <p>{{ error }}</p>
         {% endfor %}
      </div>
      <br>
      <div>{{ form.submit(
         style ='background-color: #4CAF50;
         color: white;
         width: 50%;
         padding: 14px 20px;
         margin: 8px 0;
         border: none;
         border-radius: 4px') }}
      </div>
   </form>

   <a href="{{url_for('main_bp.my_decks', email=email)}}" class="my_decks">Go to My Decks</a>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='flip-card.js') }}"></script>
{% endblock %}

flashcardz_app/templates/my_decks.html
{% extends 'layout.html' %}
{% block content %}
    <h1>FLASHCARDZ</h1>
    <h2>MY DECKS</h2>	
    <div id="decks">
        <a href="{{url_for('main_bp.create_deck', email=email)}}" class="decks">
            <input type = "button" value = "CREATE DECK +" id="create_deck" class="deck-btn" />
        </a>
        {% for deck in user_decks %}
        <a href="{{url_for('main_bp.edit_deck', email=email, deck_id=deck.id)}}" class="decks">
            <input type = "button" value ="{{ deck.name }}" class="deck-btn" />
        </a>
        {% endfor %}
    </div>
{% endblock %}

flashcardz_app/templates/registration.html
{% extends 'layout.html' %}
{% block content %}
   <h1>FLASHCARDZ</h1>
   <h2>CREATE ACCOUNT</h2>	
   <form action="" method="post">
      {{ form.hidden_tag() }}
      <div>
         EMAIL<br> 
         {{ form.email(placeholder="Email") }}
         {% for error in form.email.errors %}
         <p>{{ error }}</p>
         {% endfor %}
      </div>
      <br>

      <div>
         PASSWORD<br> 
         {{ form.password1(placeholder="Password") }}
         {% for error in form.password1.errors %}
         <p>{{ error }}</p>
         {% endfor %}
      </div>
      <br>

      <div>
         CONFIRM PASSWORD<br>
         {{ form.password2(placeholder="Confirm Password") }}
         {% for error in form.password2.errors %}
         <p>{{ error }}</p>
         {% endfor %}
      </div>
      <br>

      <div>
         {{ form.submit }}
      </div>
      <br>

   </form>
   <p class="alt-auth"><a href="{{ url_for('auth_bp.login') }}">Already have an account? Log in!</a></p>
{% endblock %}

flashcardz_app/templates/study.html
{% extends 'layout.html' %}
{% block content %}

<div class="h3-container">
   <h3><a href="{{ url_for('main_bp.my_decks', email=current_user.email) }}">My Decks</a></h3>
   <h3><a href="{{ url_for('main_bp.edit_deck', email=current_user.email, deck_id=card.deck_id) }}">Deck Overview</a></h3>
</div>

<h1>FLASHCARDZ</h1>
<h2>STUDY DECK: {{ deck_name }} </h2>

<div class="study-container">
   <div class="card" flipped="false">
       <div class="card-inner">
          <div class="card-front">
            <div class="side-text">
               <h3>Front: </h3>
               <p>{{ card.front }}</p>
            </div>
             <div class="btn-container">
                <button class="flip-btn" type="button">Check</button>
             </div>
          </div>
          <div class="card-back">
            <div class="side-text">
               <h3>Back: </h3>
               <p>{{ card.back }}</p>
            </div>
            <div class="btn-container">
               <div class="score-btns">
                  <button class="correct-btn incor" type="button" correct='false'>Incorrect</button>
                  <button class="correct-btn cor" type="button" correct='true'>Correct</button>
               </div>
               <br>
               <button class="retry-btn" type="button">Retry</button>
            </div>
         </div>
      </div>
   </div>
</div>
<p>{{ cards }}</p>
<a href="{{ url_for('main_bp.study', deck_id=deck_id, card_id=card_id ) }}">
   <button class="next-btn">Next Card</button>
</a>



 <script>
    const score_route = "{{ url_for('main_bp.record_score') }}"
   
   // https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
    async function putScore(url, data) {
      const response = await fetch(score_route, {
         method: 'PUT', 
         mode: 'cors', 
         cache: 'no-cache', 
         credentials: 'same-origin',
         headers: {
            'Content-Type': 'application/json'
         },
         redirect: 'follow',
         referrerPolicy: 'no-referrer',
         body: JSON.stringify(data)
      });
      return response;
   }

   const correctBtn = document.querySelectorAll(".correct-btn")
   
   function recordScore(e) {
      correctBtn.forEach(btn => btn.disabled = true);
      const correct = e.target.getAttribute("correct");
      const isCorrect = (correct === 'true');
      putScore(score_route, {
         correct: isCorrect,
         card_id: "{{ card.id }}",
      }).then(data => {
         console.log(data);
      })
    }
    correctBtn.forEach(btn => {
       btn.addEventListener("click", recordScore);
      })
      
   const retryBtn = document.querySelector(".retry-btn");
   retryBtn.addEventListener("click", e => {
      const card = document.querySelector(".card");
      card.setAttribute("flipped", "false");
      correctBtn.forEach(btn => btn.disabled = false);
   });

 </script>
 {% endblock %}


{% block scripts %}
<script src="{{ url_for('static', filename='flip-card.js') }}"></script>

{% endblock %}